### ISSUE TITLE
Errors when run example 'Cu_111_pole_figure.py'

### ISSUE THREAD

**Issue by fangchizhou** [heprom/pymicro#8]
Dear developers 
Thanks for creating the package which is exactly what I need for my project. However, when I tried to run the example Cu_111_pole_figure.py, it shows errors below ( I'm using python 3.6 on Pycharm on Windows 10). Really appreciate it if you can give me some feedback. 

Regards

E:\untitled\venv\Scripts\python.exe E:/untitled/test.py
Traceback (most recent call last):
  File "E:/untitled/test.py", line 13, in <module>
    micro = Microstructure(name='Cu_111')
  File "F:\pymicro\pymicro\crystal\microstructure.py", line 1452, in __init__
    overwrite_hdf5, autodelete, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 218, in __init__
    self._init_file_object(sample_name, sample_description, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 1712, in _init_file_object
    self.h5_dataset = tables.File(self.h5_file, mode='r+')
  File "C:\Users\fangc\AppData\Local\Programs\Python\Python36\lib\site-packages\tables\file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables\hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5F.c", line 509, in H5Fopen
    unable to open file
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fint.c", line 1652, in H5F_open
    unable to read superblock
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fsuper.c", line 623, in H5F__super_read
    truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048

End of HDF5 error back trace

Unable to open/create file 'Cu_111_data.h5'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "F:\pymicro\pymicro\core\samples.py", line 230, in __del__
    self.sync()
  File "F:\pymicro\pymicro\core\samples.py", line 478, in sync
    self.add_attributes(dic=self.content_index, nodename='/Index')
AttributeError: 'Microstructure' object has no attribute 'content_index'

**Comment by heprom** [comment]
Hi Fangchizhou,
I see the problem, we have recently (version 0.5.0) modified significantly how the Microstructure class works (now based on hdf5 to support large 3D microstructures). As a results, some of the examples are broken, I will fix it, thank you for letting me know.
Henry

**Comment by heprom** [comment]
Hi Fangchizhou,
I corrected the problem,you can use the last published version on pypi (0.5.1) or the master branch from the repository. Please let me know if everything is working for you.
Regards
Henry

**Comment by fangchizhou** [comment]
Hi Henry

Thank you very much. Really appreciate your help.

Regards
Chizhou

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
