### ISSUE TITLE
Issue of Microstructure class

### ISSUE THREAD

**Issue by fangchizhou** [heprom/pymicro#9]
Dear developers
Thank you very much for your previous help. I tried the 0.5.1 vision and the example "Au_6grains_pole_figure.py". However, it still shows the same error as below. Really appreciate it if you can help with it. I use pycharm python 3.7 in windows 10. 
Thanks.

Regards
Chizhou

E:\untitled1\venv\Scripts\python.exe E:/untitled1/test.py
Traceback (most recent call last):
  File "E:/untitled1/test.py", line 15, in <module>
    micro = Microstructure(name='Au_6grains')
  File "F:\pymicro\pymicro\crystal\microstructure.py", line 1454, in __init__
    overwrite_hdf5, autodelete, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 218, in __init__
    self._init_file_object(sample_name, sample_description, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 1718, in _init_file_object
    self._init_data_model()
  File "F:\pymicro\pymicro\core\samples.py", line 1782, in _init_data_model
    indexname=key)
  File "F:\pymicro\pymicro\core\samples.py", line 851, in add_data_array
    self.add_attributes(dic={'empty': True}, nodename=name)
  File "F:\pymicro\pymicro\core\samples.py", line 973, in add_attributes
    Node = self.get_node(nodename)
  File "F:\pymicro\pymicro\core\samples.py", line 1116, in get_node
    node = self.h5_dataset.get_node(node_path)
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 432, in get_node
    node = self.node_factory(key)
  File "E:\untitled1\venv\lib\site-packages\tables\group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "E:\untitled1\venv\lib\site-packages\tables\group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/CellData\mask``
Closing remaining open files:Au_6grains_data.h5...done
Exception ignored in: <function SampleData.__del__ at 0x000001B2A8CA20D8>
Traceback (most recent call last):
  File "F:\pymicro\pymicro\core\samples.py", line 230, in __del__
    self.sync()
  File "F:\pymicro\pymicro\core\samples.py", line 478, in sync
    self.add_attributes(dic=self.content_index, nodename='/Index')
  File "F:\pymicro\pymicro\core\samples.py", line 973, in add_attributes
    Node = self.get_node(nodename)
  File "F:\pymicro\pymicro\core\samples.py", line 1100, in get_node
    node_path = self._name_or_node_to_path(name)
  File "F:\pymicro\pymicro\core\samples.py", line 1987, in _name_or_node_to_path
    if self.h5_dataset.__contains__(name_tmp):
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 2049, in __contains__
    self.get_node(path)
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 1628, in get_node
    self._check_open()
  File "E:\untitled1\venv\lib\site-packages\tables\file.py", line 2150, in _check_open
    raise ClosedFileError("the file object is closed")
tables.exceptions.ClosedFileError: the file object is closed

Process finished with exit code 1

**Comment by heprom** [comment]
Hi fangchizou,

could you try to remove files `Au_6grains_data.h5` and `Au_6grain_data.xdmf` or alternatively add the option `overwrite_hdf5=True` to this line ?

**Comment by fangchizhou** [comment]
Hi I tried only run one command 
micro = Microstructure(), it shows same error massage like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\pymicro\pymicro\crystal\microstructure.py", line 1455, in __init__
    overwrite_hdf5, autodelete, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 218, in __init__
    self._init_file_object(sample_name, sample_description, **keywords)
  File "F:\pymicro\pymicro\core\samples.py", line 1736, in _init_file_object
    self._init_data_model()
  File "F:\pymicro\pymicro\core\samples.py", line 1782, in _init_data_model
    indexname=key)
  File "F:\pymicro\pymicro\core\samples.py", line 851, in add_data_array
    self.add_attributes(dic={'empty': True}, nodename=name)
  File "F:\pymicro\pymicro\core\samples.py", line 973, in add_attributes
    Node = self.get_node(nodename)
  File "F:\pymicro\pymicro\core\samples.py", line 1116, in get_node
    node = self.h5_dataset.get_node(node_path)
  File "C:\Users\fangc\Anaconda3\envs\python35\lib\site-packages\tables\file.py", line 1651, in get_node
    node = self._get_node(nodepath)
  File "C:\Users\fangc\Anaconda3\envs\python35\lib\site-packages\tables\file.py", line 1599, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "C:\Users\fangc\Anaconda3\envs\python35\lib\site-packages\tables\file.py", line 437, in get_node
    node = self.node_factory(key)
  File "C:\Users\fangc\Anaconda3\envs\python35\lib\site-packages\tables\group.py", line 1182, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "C:\Users\fangc\Anaconda3\envs\python35\lib\site-packages\tables\group.py", line 399, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/CellData\mask``

**Comment by heprom** [comment]
can you try the following:
`micro = Microstructure(name='Au_6grains', overwrite_hdf5=True)`

**Comment by heprom** [comment]
I'm closing this issue which should be resolved with the recent versions.
